#!/bin/bash
export DIRMAIN="$HOME/.config/flora"

# FUNCS

HELPER() {
	echo -e "usage: flora ..."
	echo -e "	General Usage:"
	echo -e "		-h | --help	= help message"
	echo -e "		-a | --about	= about message"
	echo -e "		-p | --pass	= set server password"
	echo -e "		-s | --server	= run in server mode"
	echo -e "		   |		= run in client mode"
	echo -e ""
}
ABOUT() {
	echo -e ""
	echo -e "	Flora [v0.1]"
	echo -e "	By Tina_lel"
	echo -e "	GitHub: https://github.com/Tina-lel"
	echo -e ""
}
GENERAL_CONFIGURATION() {
	if [[ ! -d "$DIRMAIN" ]];
	then
		mkdir -p "$DIRMAIN"
		mkdir -p "$DIRMAIN/tmp"
		mkdir -p "$DIRMAIN/server"
		touch "$DIRMAIN/server/main"
		touch "$DIRMAIN/server/send"
		touch "$DIRMAIN/server.cfg"
		touch "$DIRMAIN/client.cfg"
		echo -e "# GENERAL CONFIG\n\nOPORT=\"1234\"\nIPORT=\"1235\"\nCOMPORT=\"1236\"" > "$DIRMAIN/server.cfg"
		echo -e "# SERVER CONFIG\n\nHOST=\"127.0.0.1\"\nOPORT=\"1234\"\nIPORT=\"1235\"\nCOMPORT=\"1236\"\n\n# GENERAL CONFIG\n\nNAME=\"User\"" > "$DIRMAIN/client.cfg"
	fi
}
ENCRYPT_MAIN() {
	gpg -c --cipher-algo AES256 --batch --yes --passphrase-file $DIRMAIN/server/pass $DIRMAIN/server/main > /dev/null 2>&1
}
CHAT_GET() {
	socat -u tcp:$HOST:$OPORT - | gpg -q -d -o "$DIRMAIN/tmp/main" --cipher-algo AES256 --batch --yes --passphrase $PASS -
	clear
	echo -e "$(cat $DIRMAIN/tmp/main)"
	rm "$DIRMAIN/tmp/main"
}
WAIT_LOOP() {
	while :
	do
		socat -d0 tcp:$HOST:$COMPORT,forever - || break
		SOCAT_PID=$!
		CHAT_GET
		sleep 1.25
	done &
	LOOP_PID=$!
}
JOIN_MESSAGE() {
	echo " >> \e[3mUser $NAME has joined the chat\e[m << " | gpg -c --cipher-algo AES256 --batch --yes --passphrase $PASS - | socat -U tcp:$HOST:$IPORT -
}
LEAVE_MESSAGE() {
	echo " << \e[3mUser $NAME has left the chat\e[m >> " | gpg -c --cipher-algo AES256 --batch --yes --passphrase $PASS - | socat -U tcp:$HOST:$IPORT -
}
SOCAT_KILLER() {
	kill $LOOP_PID
	kill -9 $SOCAT_PID > /dev/null 2>&1
}
CLIENT_SOFT_EXITER() {
	printf "\e[?1049l"
	exit
}
CLIENT_EXITER() {
	LEAVE_MESSAGE
	SOCAT_KILLER
	printf "\e[?1049l"
	exit
}
SERVER_EXITER() {
	killall "socat" > /dev/null 2>&1
	exit
}

# Programm Start
GENERAL_CONFIGURATION

case $1 in
	-h | --help)
		HELPER
	;;
	-a | --about)
		ABOUT
	;;
	-p | --pass)
		echo -e "set an encryption password for the server"
		echo -e -n "\e[1;32mPassword >>\e[m "
		read -r -e PASS
		echo -e $PASS > $DIRMAIN/server/pass
		echo -e "saved Password to \"$DIRMAIN/server/pass\" IN PLAINTEXT!!!"
	;;
	-s | --server)
		source "$HOME/.config/flora/server.cfg"

		#traps
		trap "SERVER_EXITER" SIGINT

		if [[ ! -f $DIRMAIN/server/pass ]];
		then
			echo -e "you need to run -p/--pass first, to set an encryption password"
		else
			echo -e "Starting in Server Mode..."
			if [[ ! -f "$DIRMAIN/server/main.gpg" ]];
			then
				ENCRYPT_MAIN
			fi

			#OUTPUT
			socat -d0 -U tcp-l:$OPORT,fork,reuseaddr,reuseport open:"$DIRMAIN/server/main.gpg" &

			#INPUT
			while :
			do
				socat -d0 -u tcp-l:$IPORT,reuseaddr,reuseport open:"$DIRMAIN/tmp/tmp.gpg",creat || break
				gpg -q -o "$DIRMAIN/tmp/tmp" -d --cipher-algo AES256 --batch --yes --passphrase-file $DIRMAIN/server/pass $DIRMAIN/tmp/tmp.gpg
				GPG_FAIL=$?
				if [[ $GPG_FAIL != "0" ]];
				then
					rm "$DIRMAIN/tmp/tmp.gpg"
					continue
				else
					date "+%T | %d.%m.%Y" >> $DIRMAIN/server/main
					cat $DIRMAIN/tmp/tmp >> $DIRMAIN/server/main
					echo -e "------------" >> $DIRMAIN/server/main
					rm "$DIRMAIN/tmp/tmp"
					rm "$DIRMAIN/tmp/tmp.gpg"
					ENCRYPT_MAIN
					while :
					do
						socat -d0 tcp-l:$COMPORT,reuseaddr,reuseport,fork open:"$DIRMAIN/server/send" &
						SOCAT_PID=$!
						sleep 1.25
						kill $SOCAT_PID
						break
					done &
				fi
			done &

			# Server Console
			while :
			do
				read -re -p "Flora Server >> " MAIN
				case $MAIN in
					help)
						echo -e " help	= help message"
						echo -e " info	= show server info"
						echo -e " exit	= shutdown server"
					;;
					info)
						echo -e " OPORT = $OPORT"
						echo -e " IPORT = $IPORT"
						echo -e " COMPORT = $COMPORT"
					;;
					exit)
						SERVER_EXITER
					;;
					"")
					;;
					*)
						echo "No such Command \"$MAIN\""
					;;
				esac
			done
		fi
	;;
	*)
		printf "\e[?1049h"
		source "$HOME/.config/flora/client.cfg"
		clear

		#trap when not connected
		trap "CLIENT_SOFT_EXITER" SIGINT

		echo -e "Starting in Client Mode..."
		echo -e -n "\e[1;32mPassword for $HOST >>\e[m "
		read -s -r -e PASS

		trap "CLIENT_EXITER" SIGINT

		JOIN_MESSAGE
		WAIT_LOOP

		while :
		do
			read -r -e MSG
			case $MSG in
			"!q")
				CLIENT_EXITER
			;;
			*)
				echo "$NAME: $MSG" | gpg -c --cipher-algo AES256 --batch --yes --passphrase $PASS - | socat -U tcp:$HOST:$IPORT -
			;;
			esac
		done
	;;
esac
